apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notepad-deployment-testing
  labels:
    app: notepad
    env: testing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notepad
        env: testing
    spec:
      containers:
      - name: notepad-testing
        image: NOTEPAD_CONTAINER_IMAGE
        ports:
        - name: http-port
          containerPort: 8080
        volumeMounts:
        - name: notepad-logback-volume
          mountPath: /etc/notepad
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: testing
          - name: testing_datasource_url
            value: jdbc:mysql://mysql-service-testing:3306/notepad
          - name: testing_datasource_username
            value: root
          - name: testing_datasource_password
            value: root
          - name: JVM_ARGS
            value: "-Xmx256m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
          timeoutSeconds: 3
      volumes:
      - name: notepad-logback-volume
        configMap:
          name: notepad-logback-testing-configmap
